<a href="https://colab.research.google.com/github/mohammadsanatabassum/labs-and-projects-on-aiml-/blob/main/basics_of_linear_alg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print ("Matrix and its Transpose")
a = np.array([[1,2,3],[2,3,4]])
b = a.T
print('a\n',a)
print('b\n',b)

Matrix and its Transpose
a
 [[1 2 3]
 [2 3 4]]
b
 [[1 2]
 [2 3]
 [3 4]]


In [9]:
a = 5
b = 6
z = np.dot(a,b)
print(z)

30


In [14]:
 # 2D arrays or matrices
 a = [[1,2,3],[9,5,3],[7,2,-5]]
 b = [[3,-1,5],[-2,-6,4], [0,4,4]]
 z = np.dot(a,b)
 print(z)


[[ -1  -1  25]
 [ 17 -27  77]
 [ 17 -39  23]]


In [18]:
  # 1D arrays or vectors
  a = np.array([1,2,3])  # or a = [1,2,3]
  b = np.array([2,6,2])  # or b = [2,3,4]
  z = np.dot(a,b)
  print(z)


20


In [19]:
 z = np.matmul(a,b)
 print(z)

20


In [21]:
# convert lists into NumPy arrays
newa = np.array(a)
newb = np.array(b)
z = newa.dot(newb)
print(z)


20


In [22]:
 # matrices with random integers: entries ranging from -4 to 4
 a = np.random.randint(-4,4,(500,5))
 b = np.random.randint(-4,4,(5,1000))
 c = np.random.randint(-4,4,(1000,10))
 d = np.random.randint(-4,4,(10,2000))
 e = np.random.randint(-4,4,(2000,200))
 z = np.linalg.multi_dot([a,b,c,d,e])

In [25]:
a = np.array([[1,2,1], [4,-1,0]])
b = np.array([3,3,3])
z = np.inner(a,b)
print(z)


[12  9]


In [26]:
a.dot(b.T)

array([12,  9])

In [27]:
 a = np.array([11,2,0,4,7])
 b = np.array([6,3,0])
 z = np.outer(a,b)
 print(z)

[[66 33  0]
 [12  6  0]
 [ 0  0  0]
 [24 12  0]
 [42 21  0]]


In [34]:
 a = np.random.random([3,2,5])
 b = np.random.random([3,5,3])
 z = a @ b
 print(z.shape)

(3, 2, 3)


In [37]:
 a = np.random.randint(1,10,[4,4])
 det = np.linalg.det(a)
 print(int(det))

450


In [38]:
a = np.random.randint(1,10,[4,4])
inv = np.linalg.inv(a)
print(a)
print()
print(inv)



[[9 2 8 2]
 [3 4 6 9]
 [4 1 7 3]
 [9 8 6 1]]

[[ 0.30689655  0.05344828 -0.34482759 -0.06034483]
 [-0.21206897 -0.00603448  0.10344828  0.16810345]
 [-0.19827586 -0.09913793  0.4137931   0.04741379]
 [ 0.12413793  0.16206897 -0.20689655 -0.0862069 ]]


In [39]:
 a = np.random.random([5,5])
 # positive powers of matrix
 a_2 = np.linalg.matrix_power(a, 2)
 a_7 = np.linalg.matrix_power(a, 7)
 # inverse of matrix
 a_inv_1 = np.linalg.matrix_power(a, -1)
 a_inv_3 = np.linalg.matrix_power(a, -3)

 print('matrix \n',a)
 print('\n matrix to the power 2\n',a_2)
 print('\n matrix to the power 7\n',a_7)
 print('\n matrix inverse \n',a_inv_1)
 print('\n matrix cubic inverse \n',a_inv_3)

matrix 
 [[0.48790729 0.41861555 0.50382718 0.98674561 0.64667086]
 [0.36134626 0.81948178 0.76148368 0.43396476 0.84442615]
 [0.57170983 0.75964088 0.99830838 0.70232027 0.93932153]
 [0.97726522 0.94768706 0.99391861 0.11269006 0.44917134]
 [0.75276312 0.10720062 0.02667695 0.51249804 0.67193167]]

 matrix to the power 2
 [[2.12846377 1.93447068 2.06556079 1.45956678 2.01999754]
 [1.96751938 1.90305548 2.02012598 1.72865874 2.40326316]
 [2.51761728 2.38647002 2.58622414 2.15546671 2.89552329]
 [1.83573873 2.09567826 2.33024556 2.31652262 2.71825942]
 [1.42791852 0.98095145 1.0148323  1.21015986 1.28406281]]

 matrix to the power 7
 [[577.29525085 538.14651054 578.91890934 513.77353867 654.37762195]
 [594.9293681  554.56527844 596.57401035 529.3468288  674.2837669 ]
 [747.96112478 697.21296402 750.02787604 665.5252932  847.73672432]
 [674.94859946 629.09821649 676.7376873  600.35466616 764.82669819]
 [352.91959056 328.96599339 353.88331101 314.00417838 399.99007406]]

 matrix inverse 


In [43]:

a = np.arange(9).reshape(3,3)
eig_val, eig_vec = np.linalg.eig(a)
print('Eigenvalues are: \n', eig_val)
print('\nEigenvectors are: \n', eig_vec)

Eigenvalues are: 
 [ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]

Eigenvectors are: 
 [[ 0.16476382  0.79969966  0.40824829]
 [ 0.50577448  0.10420579 -0.81649658]
 [ 0.84678513 -0.59128809  0.40824829]]


In [45]:
a = np.arange(9).reshape(3,3)
eigenvalues = np.linalg.eigvals(a)
print(eigenvalues)

[ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]


In [46]:
a = np.eye(8)
print(a)
z = np.trace(a)
print('\nTrace of matrix is: ',z)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

Trace of matrix is:  8.0


In [47]:
a = np.arange(16).reshape(4,4)
z = np.linalg.norm(a)
print(a)
print('\n Frobenius Norm of above matrix:')
print(z)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 Frobenius Norm of above matrix:
35.21363372331802


In [48]:
# Norm along axis 0
a = np.arange(20).reshape(4,5)
z = np.linalg.norm(a, axis=0)
print(z)

[18.70828693 20.34698995 22.04540769 23.79075451 25.57342371]


In [51]:
# Coefficient Matrix
a = np.random.randint(1,20,[4,4])
# Dependent variable vector
b = np.array([4,9,12,7])
# solution
x = np.linalg.solve(a,b)
print('Coefficient Matrix')
print(a)
print('\nDependent Variable vector')
print(b)
print('\nSolution')
print(x)

Coefficient Matrix
[[ 6 13 14 13]
 [10  8 17  5]
 [ 8 17 12 17]
 [10  6 11 19]]

Dependent Variable vector
[ 4  9 12  7]

Solution
[ 2.17512574  0.85962506 -1.02011888 -0.45724737]


In [52]:
# Check for correctness
B = a.dot(x)
print(B)

[ 4.  9. 12.  7.]
